### ISSUE TITLE
The message "Link copied!" does not show

### ISSUE THREAD

**Issue by hechangran** [Panopto-Video-DL/Panopto-Video-DL-browser#1]
The script works perfectly last week. However, it starts to not show 'Link copied!' message after I click the download button today. Instead, it will pop out a new page containing the .mp4 file of the lecture. The quality of the .mp4 file on the new page is much lower than those previous lectures that I have downloaded. 

I wonder if there is any fix for this problem? Thank you!

**Comment by pizidavi** [comment]
> Instead, it will pop out a new page containing the .mp4 file of the lecture.

This is not a bug, if it's an .mp4 file it's faster to download it via the three dots in the bottom right corner (if you're using Chrome) or by right-clicking on the video.

> The quality of the .mp4 file on the new page is much lower than those previous lectures that I have downloaded.

Sorry, I can't do anything about that 🙁

**Comment by hechangran** [comment]
> > Instead, it will pop out a new page containing the .mp4 file of the lecture.
> 
> This is not a bug, if it's an .mp4 file it's faster to download it via the three dots in the bottom right corner (if you're using Chrome) or by right-clicking on the video.
> 
> > The quality of the .mp4 file on the new page is much lower than those previous lectures that I have downloaded.
> 
> Sorry, I can't do anything about that 🙁

Thank you for the reply. Is it true that the script will not show "Link copied!" for a Panopto video that turns out to be a .mp4 file? It seems that downloading the video via Panopto-Video-DL_win-x64.exe will have a better resolution. Thus, I wonder if there is a way to get the link and download the video via Panopto-Video-DL_win-x64.exe instead of using download button in three dots in the bottom right corner?

**Comment by pizidavi** [comment]
> Is it true that the script will not show "Link copied!" for a Panopto video that turns out to be a .mp4 file?

Yes, that's right

> I wonder if there is a way to get the link and download the video via Panopto-Video-DL_win-x64.exe instead of using download button in three dots in the bottom right corner?

You can copy the link of the new tab and paste it in Panopto-Video-DL, the program can also download .mp4 files (from version 3.1 onwards), but I don't thing that the quality will change so much

**Comment by hechangran** [comment]
> > Is it true that the script will not show "Link copied!" for a Panopto video that turns out to be a .mp4 file?
> 
> Yes, that's right
> 
> > I wonder if there is a way to get the link and download the video via Panopto-Video-DL_win-x64.exe instead of using download button in three dots in the bottom right corner?
> 
> You can copy the link of the new tab and paste it in Panopto-Video-DL, the program can also download .mp4 files (from version 3.1 onwards), but I don't thing that the quality will change so much

Thank you for your detailed explanation!
