### ISSUE TITLE
Don't see video Download button

### ISSUE THREAD

**Issue by coveringspaces** [Panopto-Video-DL/Panopto-Video-DL-browser#10]
I followed all of the installation steps, but I do not see the download button in the bottom left hand corner. I'm wondering what might be going wrong.

**Comment by pizidavi** [comment]
This is what you should see
![image](https://github.com/user-attachments/assets/7ad97c06-e116-4cbc-ac8a-a491d8168da8)

This script currently work with `*.panopto.com` and `*.panopto.eu`, if your Panopto instance base url is different let me know so I can update the domain

If the domain is correct, can give me the logs from the browser console?

**Comment by coveringspaces** [comment]
Yes, I am using a *.panopto.com base url, so I have attached my logs to this message. Hope this is what you wanted. If not, let me know!
[harvard.hosted.panopto.com-1727387798417.log](https://github.com/user-attachments/files/17156414/harvard.hosted.panopto.com-1727387798417.log)

**Comment by pizidavi** [comment]
Can you install this new version and try again?

I added a new button in the Tampermonkey menu
![image](https://github.com/user-attachments/assets/b4b1b827-648c-4c9f-93e1-2ce07d64bc9c)

[Panopto-Video-DL.txt](https://github.com/user-attachments/files/17175947/Panopto-Video-DL.txt)

**Comment by coveringspaces** [comment]
<img width="260" alt="Screenshot 2024-09-30 at 3 28 10 PM" src="https://github.com/user-attachments/assets/253905b3-e6b8-4fd2-98a9-450164e343cd">

Somehow I still don't see the download button, so odd. 

Just to confirm that I installed the script correctly, I just created a new script in TamperMonkey and then copy and pasted the .txt file you provided. That should work, right?

**Comment by pizidavi** [comment]
Sorry for the delay.
Yes, what you did should be correct.
Can I see the console logs?
What version of Tampermonkey are you using?

The end of the _pathname_ url with be `/Viewer.aspx`, is that the same for you?

**Comment by pestylucas** [comment]
I also seem to be having this issue? is there a solution you found?

**Comment by pizidavi** [comment]
@pestylucas The end of the _pathname_ url with be `/Viewer.aspx`, is that the same for you?

Can you send me the console logs?
What version of Tampermonkey are you using?

**Comment by OranSimon** [comment]
Is that possible to download a video with /Embed.aspx ?

**Comment by emily7z** [comment]
I am also having the same issue, my path is Viewer.aspx?id=xxxx. I m using v5.3.2.
[panopto.com-1732132856547.log](https://github.com/user-attachments/files/17836161/panopto.com-1732132856547.log)

**Comment by pizidavi** [comment]
Hi @emily7z , did you update to Panopto-Video-DL-browser version 3.4.0? Are you able to see the Download button in the Tampermonkey menu?

Please resend me the log following this steps:
1. Open a lesson on Panopto
2. Open the browser console: right-click on the page and select "Inspect"
3. Reload the page
4. You should see a log "Panopto-Video-DL -> Service started"

Copy everything there and send it to me
I think Panopto change a bit the UI, but I'm using a older version

**Comment by ReoCSun** [comment]
@emily7z did you turn on [developer mode ](https://www.tampermonkey.net/faq.php?locale=en#:~:text=Steps%20to%20Enable%20Developer%20Mode&text=Open%20the%20menu%2C%20select%20%22Extensions,navigate%20to%20the%20extensions%20page.&text=Find%20and%20click%20the%20%22Developer,top%20right%20to%20enable%20it.)for Tampermonkey?
