### ISSUE TITLE
[Download] Button not showing

### ISSUE THREAD

**Issue by nuson999** [Panopto-Video-DL/Panopto-Video-DL-browser#4]
[Download] button in the bottom-left corner is not visible.

I have tried so far: 
1. Refresh the page
2. Reinstall the script from greasyfork

**Comment by pizidavi** [comment]
Have you solved it?

**Comment by nuson999** [comment]
> Have you solved it?

Yes, I found that the match URL was wrong.

**Comment by pizidavi** [comment]
Could you tell me the match URL? So I make it available to everyone
Or you can make a Pull Request

**Comment by nuson999** [comment]
> Could you tell me the match URL? So I make it available to everyone
> Or you can make a Pull Request

It seems that my code had somehow gone wrong.  There is no problem with the code in the repo :)

I did git clone again, and the problem was solved.
