### ISSUE TITLE
Unable to Retrieve VideoID/LessonID

### ISSUE THREAD

**Issue by neonautumn** [Panopto-Video-DL/Panopto-Video-DL-browser#5]
This may just be because of some organization-level setting my institution uses, but it seems that the current build is unable to retrieve the videoID/LessonID.

**Comment by pizidavi** [comment]
Are you getting an error notification `Failed to get Lesson ID`?

The lesson ID should be in the url `/Panopto/Pages/Viewer.aspx?id=aaaaa-aaaa`.
Does your Panopto have a different behavior?
