### ISSUE TITLE
Able to merge video and slide for some lectures, but not all

### ISSUE THREAD

**Issue by yeewantung** [Panopto-Video-DL/Panopto-Video-DL-browser#6]
Thanks for providing the tool! However, I noticed that usually the original video containing the lecturer will be reshaped to a small block on the bottom right corner and the main content would be the slides. But for some lectures, the generated video is only the lecturer view without the slides, as follows
<img width="1013" alt="image" src="https://github.com/Panopto-Video-DL/Panopto-Video-DL-browser/assets/51008065/dc2e0966-6119-4949-aac2-49bfa6cb315d">

I've tried a few times and it still appears like that. Is this a bug or is there anything I should do to make the merging successful?

**Comment by pizidavi** [comment]
This is not a bug, there is no video merging. The downloaded video is taken directly from Panopto.
The only thing you can do is to download the separate video sources and merge them yourself.

After clicking "Download" on the Panopto website, a black modal should appear showing the other video sources _if available_.
If you clicked on "Close and don't show again", clear the `localStorage`.

**Comment by yeewantung** [comment]
Interesting to know. It seems that for some Panopto lectures in the same course, the video extracted is just the merged one, like the following:

<img width="1084" alt="image" src="https://github.com/Panopto-Video-DL/Panopto-Video-DL-browser/assets/51008065/d1add005-d5f9-4a3c-bbfe-fc2996cf544d">

So does it mean that this is an issue of Panopto itself? For those lectures of which the video is just the lecturer along, it is the Panopto that provides a source video like that.

**Comment by pizidavi** [comment]
Yes, exactly

**Comment by yeewantung** [comment]
Thanks for the help!
